#https://developer.hashicorp.com/consul/tutorials/kubernetes/kubernetes-deployment-guide
# Enable and configure the Consul UI.
ui:
  enabled: true
  service:
    type: LoadBalancer
# Configure global settings in this section.
global:
  name: consul
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  # Gossip encryption
  gossipEncryption:
    autoGenerate: true
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 1
  # Specify the resources that servers request for placement. These values will serve a large environment.
#  resources:
#    requests:
#      memory: '32Gi'
#      cpu: '4'
#      disk: '30Gi'
#    limits:
#      memory: '32Gi'
#      cpu: '4'
#      disk: '50Gi'
  # If using Enterprise, reference the Kubernetes secret that holds your license here
#  enterpriseLicense:
#    secretName: 'consul-license'
#    secretKey: 'key'
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources:
    requests:
      memory: '8Gi'
      cpu: '2'
      disk: '15Gi'
    limits:
      memory: '8Gi'
      cpu: '2'
      disk: '15Gi'

# Enable Consul connect pod injection
connectInject:
  enabled: true
  default: true
controller:
  enabled: true

# Reach Other DC
#meshGateway:
#  enabled: true
#  replicas: 1
