# https://developer.hashicorp.com/consul/tutorials/kubernetes/kubernetes-deployment-guide
# https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
# Enable and configure the Consul UI.
ui:
  enabled: true
  service:
    type: LoadBalancer

global:
  # The main enabled/disabled setting.
  # If true, servers, clients, Consul DNS and the Consul UI will be enabled.
  enabled: true
  # The prefix used for all resources created in the Helm chart.
  name: consul
  # The consul image version.
#  image: hashicorp/consul:1.16.0
  # The name of the datacenter that the agents should register as.
  datacenter: gcp-dev
  # Enables TLS across the cluster to verify authenticity of the Consul servers and clients.
  tls:
    enabled: true
  # Enables ACLs across the cluster to secure access to data and APIs.
  acls:
    # If true, automatically manage ACL tokens and policies for all Consul components.
    manageSystemACLs: true

server:
  enabled: true
  # The number of server agents to run. This determines the fault tolerance of the cluster.
  replicas: 1

# Enable Consul connect pod injection
connectInject:
  enabled: true
  default: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer

# Reach Other DC
#meshGateway:
#  enabled: true
#  replicas: 1
